/*
 * This file is generated by jOOQ.
 */
package com.liubomyr.voucher.database.schema;


import com.liubomyr.voucher.database.schema.tables.Country;
import com.liubomyr.voucher.database.schema.tables.Currency;
import com.liubomyr.voucher.database.schema.tables.Customer;
import com.liubomyr.voucher.database.schema.tables.Hotel;
import com.liubomyr.voucher.database.schema.tables.Nutrition;
import com.liubomyr.voucher.database.schema.tables.Transport;
import com.liubomyr.voucher.database.schema.tables.Type;
import com.liubomyr.voucher.database.schema.tables.Voucher;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sql4458432 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sql4458432</code>
     */
    public static final Sql4458432 SQL4458432 = new Sql4458432();

    /**
     * The table <code>sql4458432.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>sql4458432.currency</code>.
     */
    public final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>sql4458432.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>sql4458432.hotel</code>.
     */
    public final Hotel HOTEL = Hotel.HOTEL;

    /**
     * The table <code>sql4458432.nutrition</code>.
     */
    public final Nutrition NUTRITION = Nutrition.NUTRITION;

    /**
     * The table <code>sql4458432.transport</code>.
     */
    public final Transport TRANSPORT = Transport.TRANSPORT;

    /**
     * The table <code>sql4458432.type</code>.
     */
    public final Type TYPE = Type.TYPE;

    /**
     * The table <code>sql4458432.voucher</code>.
     */
    public final Voucher VOUCHER = Voucher.VOUCHER;

    /**
     * No further instances allowed
     */
    private Sql4458432() {
        super("sql4458432", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Country.COUNTRY,
            Currency.CURRENCY,
            Customer.CUSTOMER,
            Hotel.HOTEL,
            Nutrition.NUTRITION,
            Transport.TRANSPORT,
            Type.TYPE,
            Voucher.VOUCHER
        );
    }
}
