/*
 * This file is generated by jOOQ.
 */
package com.liubomyr.voucher.database.schema;


import com.liubomyr.voucher.database.schema.tables.Country;
import com.liubomyr.voucher.database.schema.tables.Currency;
import com.liubomyr.voucher.database.schema.tables.Customer;
import com.liubomyr.voucher.database.schema.tables.Hotel;
import com.liubomyr.voucher.database.schema.tables.Nutrition;
import com.liubomyr.voucher.database.schema.tables.Transport;
import com.liubomyr.voucher.database.schema.tables.Type;
import com.liubomyr.voucher.database.schema.tables.Voucher;


/**
 * Convenience access to all tables in sql4458432.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sql4458432.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>sql4458432.currency</code>.
     */
    public static final Currency CURRENCY = Currency.CURRENCY;

    /**
     * The table <code>sql4458432.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>sql4458432.hotel</code>.
     */
    public static final Hotel HOTEL = Hotel.HOTEL;

    /**
     * The table <code>sql4458432.nutrition</code>.
     */
    public static final Nutrition NUTRITION = Nutrition.NUTRITION;

    /**
     * The table <code>sql4458432.transport</code>.
     */
    public static final Transport TRANSPORT = Transport.TRANSPORT;

    /**
     * The table <code>sql4458432.type</code>.
     */
    public static final Type TYPE = Type.TYPE;

    /**
     * The table <code>sql4458432.voucher</code>.
     */
    public static final Voucher VOUCHER = Voucher.VOUCHER;
}
