/*
 * This file is generated by jOOQ.
 */
package com.liubomyr.voucher.database.schema.tables.records;


import com.liubomyr.voucher.database.schema.tables.Customer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record5<Integer, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>voucher_agency.customer.CUST_ID</code>.
     */
    public void setCustId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>voucher_agency.customer.CUST_ID</code>.
     */
    public Integer getCustId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>voucher_agency.customer.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>voucher_agency.customer.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>voucher_agency.customer.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>voucher_agency.customer.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>voucher_agency.customer.PASSPORT_CODE</code>.
     */
    public void setPassportCode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>voucher_agency.customer.PASSPORT_CODE</code>.
     */
    public Integer getPassportCode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>voucher_agency.customer.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>voucher_agency.customer.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customer.CUSTOMER.CUST_ID;
    }

    @Override
    public Field<String> field2() {
        return Customer.CUSTOMER.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.LAST_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Customer.CUSTOMER.PASSPORT_CODE;
    }

    @Override
    public Field<String> field5() {
        return Customer.CUSTOMER.EMAIL;
    }

    @Override
    public Integer component1() {
        return getCustId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public Integer component4() {
        return getPassportCode();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public Integer value1() {
        return getCustId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public Integer value4() {
        return getPassportCode();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public CustomerRecord value1(Integer value) {
        setCustId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CustomerRecord value4(Integer value) {
        setPassportCode(value);
        return this;
    }

    @Override
    public CustomerRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomerRecord values(Integer value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer custId, String firstName, String lastName, Integer passportCode, String email) {
        super(Customer.CUSTOMER);

        setCustId(custId);
        setFirstName(firstName);
        setLastName(lastName);
        setPassportCode(passportCode);
        setEmail(email);
    }
}
