/*
 * This file is generated by jOOQ.
 */
package com.liubomyr.voucher.database.schema.tables.records;


import com.liubomyr.voucher.database.schema.tables.Nutrition;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NutritionRecord extends UpdatableRecordImpl<NutritionRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>voucher_agency.nutrition.NUTRITION_ID</code>.
     */
    public void setNutritionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>voucher_agency.nutrition.NUTRITION_ID</code>.
     */
    public Integer getNutritionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>voucher_agency.nutrition.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>voucher_agency.nutrition.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>voucher_agency.nutrition.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>voucher_agency.nutrition.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Nutrition.NUTRITION.NUTRITION_ID;
    }

    @Override
    public Field<String> field2() {
        return Nutrition.NUTRITION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Nutrition.NUTRITION.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getNutritionId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getNutritionId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public NutritionRecord value1(Integer value) {
        setNutritionId(value);
        return this;
    }

    @Override
    public NutritionRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NutritionRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public NutritionRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NutritionRecord
     */
    public NutritionRecord() {
        super(Nutrition.NUTRITION);
    }

    /**
     * Create a detached, initialised NutritionRecord
     */
    public NutritionRecord(Integer nutritionId, String name, String description) {
        super(Nutrition.NUTRITION);

        setNutritionId(nutritionId);
        setName(name);
        setDescription(description);
    }
}
